[package]
name = "cypherAES"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
block-modes = "0.9"
block-padding = "0.3"
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }
base64 = "0.22"
dotenvy = "0.15"
